name: Manual Build

on:
  workflow_dispatch:

env:
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Java JDK (Make sure to specify the version needed)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Use the Java version you need

      # Step 3: Install Maven
      - name: Install Maven
        run: |
          sudo apt-get install maven

      # Step 4: Build the project (this will also run tests)
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Increment the version
      - name: Increment Version
        id: version
        run: |
          # Increment the version
          VERSION=$(echo "${{ env.VERSION }}" | awk -F. -v OFS=. '{$NF++;print}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 6: Update pom.xml with the new version
      - name: Update pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ env.VERSION }}
          mvn versions:commit

      # Step 7: Commit the updated pom.xml with the new version (only if there are changes)
      - name: Commit new version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pom.xml
          git commit -m "Bump version to ${{ env.VERSION }}" || echo "No changes to commit"

      # Step 8: Create Git Tag and push
      - name: Create Git Tag and push
        run: |
          # Create a properly formatted tag with periods
          TAG_NAME="v${{ env.VERSION }}"
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
          git push origin master
          git push origin "$TAG_NAME"

      # Step 9: Upload the JAR as an artifact (Optional)
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/*.jar # Adjust the path according to your project structure
